function renderBalances(){const v=balances[me.party_id]||0,c=$('myBalance');c.classList.remove('good','bad');$('bal').textContent=money.format(Math.abs(v));if(v===0){$('bal').textContent=money.format(0);$('bsub').textContent='Cuenta al día'}else if(v>0){c.classList.add('good');$('bsub').textContent='Te tienen que devolver'}else{c.classList.add('bad');$('bsub').textContent='Te corresponde poner'}
  $('partyGrid').innerHTML=PARTIES.map(p=>{const b=balances[p.id]||0,cls=b>0?'good':b<0?'bad':'';return `<div class="party-card ${cls} ${p.id===me.party_id?'me':''}"><div class="party-name">${esc(p.name)}${p.id===me.party_id?' · tú':''}</div><div class="party-amount">${money.format(Math.abs(b))}</div><div class="meta">${b>0?'Debe recibir':b<0?'Debe poner':'Al día'}</div></div>`}).join('')}
function suggestions(){const debtors=PARTIES.map(p=>({id:p.id,v:-(balances[p.id]||0)})).filter(x=>x.v>0.005).sort((a,b)=>b.v-a.v),creditors=PARTIES.map(p=>({id:p.id,v:balances[p.id]||0})).filter(x=>x.v>0.005).sort((a,b)=>b.v-a.v),out=[];let i=0,j=0;while(i<debtors.length&&j<creditors.length){const a=Math.min(debtors[i].v,creditors[j].v);if(a>0.005)out.push({payer:debtors[i].id,receiver:creditors[j].id,amount:a});debtors[i].v-=a;creditors[j].v-=a;if(debtors[i].v<0.005)i++;if(creditors[j].v<0.005)j++}return out}
function renderSuggestions(){const s=suggestions();$('settleCard').classList.toggle('hide',!s.length);$('settleList').innerHTML=s.map((x,i)=>`<div class="settle"><b>${esc(name(x.payer))}</b> paga <b>${money.format(x.amount)}</b> a <b>${esc(name(x.receiver))}</b><button type="button" onclick="prefillSettlement('${x.payer}','${x.receiver}',${x.amount.toFixed(2)})">Registrar</button></div>`).join('')}
window.prefillSettlement=(p,r,a)=>{form('settlement');$('payer').value=p;$('receiver').value=r;$('amount').value=a.toFixed(2);preview();$('panel').scrollIntoView({behavior:'smooth'})};
function render(){let q=$('search').value.trim().toLowerCase(),m=$('month').value,r=rows.filter(x=>(!m||x.occurred_on.startsWith(m))&&(!q||[x.item,x.supplier,x.notes,name(x.payer_party),name(x.receiver_party)].filter(Boolean).join(' ').toLowerCase().includes(q)));$('empty').classList.toggle('hide',r.length>0);$('list').innerHTML=r.map(x=>{const type=x.entry_type==='settlement'?'Pago':'Compra';let title,meta,sign='';if(x.entry_type==='settlement'){title=`${name(x.payer_party)} pagó a ${name(x.receiver_party)}`;meta=`${new Date(x.occurred_on+'T12:00').toLocaleDateString('es-ES')} · ajuste entre negocios`;if(x.payer_party===me.party_id)sign='plus';else if(x.receiver_party===me.party_id)sign='minus'}else{title=x.item||x.supplier||'Compra';const ps=(x.participants||[]).map(name).join(', ');meta=`${new Date(x.occurred_on+'T12:00').toLocaleDateString('es-ES')}${x.supplier?' · '+esc(x.supplier):''} · pagó ${esc(name(x.payer_party))} · reparto: ${esc(ps)}`;const share=(x.participants||[]).includes(me.party_id)?Number(x.amount)/(x.participants||[]).length:0;const minePay=x.payer_party===me.party_id?Number(x.amount):0;const net=minePay-share;sign=net>0.005?'plus':net<-.005?'minus':''}
    return `<article class="row ${x.status==='void'?'void':''}"><div class="rtop"><div><span class="tag">${type}${x.status==='void'?' · anulado':''}</span><b style="display:block;margin-top:5px">${esc(title)}</b><div class="meta">${meta}</div></div><div class="amt ${sign}">${money.format(Number(x.amount))}</div></div>${x.notes?`<div class="meta" style="margin-top:8px">${esc(x.notes)}</div>`:''}<div>${x.invoice_path?`<button onclick="invoiceOpen('${x.id}')">Ver factura</button>`:''}${x.status==='active'?`<button onclick="editRow('${x.id}')">Editar</button><button onclick="voidRow('${x.id}')">Anular</button>`:''}</div></article>`}).join('')}
function form(type,row){$('panel').classList.remove('hide');$('eid').value=row?.id||'';$('etype').value=type;$('ptitle').textContent=row?'Editar movimiento':type==='settlement'?'Registrar pago':'Nueva compra';$('date').value=row?.occurred_on||today();$('payer').innerHTML=partyOptions(row?.payer_party||me.party_id);$('receiver').innerHTML=partyOptions(row?.receiver_party||PARTIES.find(p=>p.id!==(row?.payer_party||me.party_id))?.id);$('amount').value=row?.amount||'';$('supplier').value=row?.supplier||'';$('item').value=row?.item||'';$('notes').value=row?.notes||'';$('invoice').value='';const expense=type==='expense';$('receiverLab').classList.toggle('hide',expense);$('supLab').classList.toggle('hide',!expense);$('itemLab').classList.toggle('hide',!expense);$('participantsLab').classList.toggle('hide',!expense);$('fileLab').classList.toggle('hide',!expense);$('participants').innerHTML=participantChecks(row?.participants||PARTIES.map(p=>p.id));bindParticipantChecks();preview();$('panel').scrollIntoView({behavior:'smooth'})}
function bindParticipantChecks(){$('participants').querySelectorAll('input').forEach(x=>x.onchange=preview)}
function preview(){const type=$('etype').value,p=$('payer').value,a=Number($('amount').value||0);if(type==='settlement'){const r=$('receiver').value;$('prev').textContent=p===r?'El pagador y quien recibe no pueden ser el mismo negocio.':`${name(p)} paga ${a?money.format(a):'el importe indicado'} a ${name(r)}. Este pago ajusta los saldos.`;return}const ps=checkedParticipants();if(!ps.length){$('prev').textContent='Marca al menos un negocio para repartir el gasto.';return}const share=a/ps.length;$('prev').textContent=`${name(p)} adelanta ${a?money.format(a):'el importe'}. Se reparte entre ${ps.length} negocio${ps.length===1?'':'s'}${a?`: ${money.format(share)} por cada uno`:''}.`}
$('buy').onclick=()=>form('expense');$('pay').onclick=()=>form('settlement');$('close').onclick=()=>$('panel').classList.add('hide');$('payer').onchange=preview;$('receiver').onchange=preview;$('amount').oninput=preview;$('search').oninput=render;$('month').onchange=render;$('refresh').onclick=refresh;
$('entry').onsubmit=async e=>{e.preventDefault();setBusy(true);try{let id=$('eid').value||null,type=$('etype').value,p=$('payer').value,a=Number($('amount').value);if(!a||a<=0)throw Error('Indica un importe válido.');let payload={entry_type:type,occurred_on:$('date').value,payer_party:p,receiver_party:null,participants:null,amount:a,supplier:null,item:null,notes:$('notes').value.trim()||null};if(type==='expense'){const ps=checkedParticipants();if(!ps.length)throw Error('Marca al menos un negocio para el reparto.');payload.participants=ps;payload.supplier=$('supplier').value.trim()||null;payload.item=$('item').value.trim()||null}else{const r=$('receiver').value;if(r===p)throw Error('El pagador y quien recibe no pueden ser el mismo.');payload.receiver_party=r}
  let row,oldPath=null;if(id){const old=rows.find(x=>x.id===id);oldPath=old?.invoice_path||null;let res=await db.from('g5_entries').update(payload).eq('id',id).select().single();if(res.error)throw res.error;row=res.data}else{payload.created_by=user.id;let res=await db.from('g5_entries').insert(payload).select().single();if(res.error)throw res.error;row=res.data}
  const f=$('invoice').files?.[0];if(type==='expense'&&f){const safe=f.name.replace(/[^a-zA-Z0-9._-]/g,'_'),path=row.id+'/'+Date.now()+'-'+safe,res=await db.storage.from('g5-invoices').upload(path,f,{upsert:false});if(res.error)toast('Movimiento guardado, pero falló la factura.');else{await db.from('g5_entries').update({invoice_path:path}).eq('id',row.id);if(oldPath&&oldPath!==path)await db.storage.from('g5-invoices').remove([oldPath]).catch(()=>{})}}
  $('panel').classList.add('hide');toast(id?'Movimiento actualizado.':'Movimiento guardado.');await refresh()
}catch(err){toast('No se pudo guardar: '+(err.message||'error'))}finally{setBusy(false)}};
window.invoiceOpen=async id=>{const r=rows.find(x=>x.id===id);if(!r?.invoice_path)return;const{data,error}=await db.storage.from('g5-invoices').createSignedUrl(r.invoice_path,120);if(error)return toast('No se pudo abrir la factura.');open(data.signedUrl,'_blank')};
window.editRow=id=>{const r=rows.find(x=>x.id===id);if(r)form(r.entry_type,r)};
window.voidRow=async id=>{if(!confirm('¿Anular este movimiento? Quedará visible como anulado.'))return;setBusy(true);try{const{error}=await db.from('g5_entries').update({status:'void',voided_by:user.id,voided_at:new Date().toISOString()}).eq('id',id);if(error)throw error;toast('Movimiento anulado.');await refresh()}catch(err){toast('No se pudo anular: '+(err.message||'error'))}finally{setBusy(false)}};
async function refresh(){await load()}
async function boot(){const{data:{user:u}}=await db.auth.getUser();if(!u){showOnly('auth');return}user=u;try{const m=await member();if(!m){$('cn').value=localStorage.getItem('g5_pending_name')||'';$('cc').value=localStorage.getItem('g5_pending_code')||'';showOnly('claim');return}showOnly('app');await refresh()}catch(e){toast(e.message||'No se pudo abrir la cuenta.');showOnly('auth')}}
boot();