(()=>{
function mrStyles(){if(document.getElementById('monthlyRatiosStyle'))return;const s=document.createElement('style');s.id='monthlyRatiosStyle';s.textContent=`.ratio-card{border-color:#3a433e}.ratio-title{font-size:1rem;font-weight:950}.ratio-help{font-size:.72rem;color:var(--muted);line-height:1.4;margin-top:4px}.ratio-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:11px}.ratio-box{border:1px solid #303833;border-radius:11px;padding:10px;background:#111613}.ratio-box span{display:block;font-size:.66rem;text-transform:uppercase;color:var(--muted)}.ratio-box strong{display:block;font-size:1rem;margin-top:3px}.ratio-box small{display:block;font-size:.68rem;color:var(--muted);margin-top:2px}.ratio-result strong{color:var(--mint)}@media(max-width:390px){.ratio-grid{grid-template-columns:1fr 1fr}}`;document.head.appendChild(s)}
function mrCountable(x){return typeof window.isAccountingDocument==='function'?window.isAccountingDocument(x):((x?.document_type||'invoice')!=='delivery_note'&&x?.document_status!=='linked')}
function mrPct(value,sales){return sales?value/sales*100:0}
function mrCard(){
  const docs=(Array.isArray(invoices)?invoices:[]).filter(x=>(x.invoice_date||'').slice(0,7)===selectedMonth&&mrCountable(x)),mv=(Array.isArray(moves)?moves:[]).filter(x=>(x.move_date||'').slice(0,7)===selectedMonth);
  const sum=(rows,key='amount')=>rows.reduce((a,x)=>a+(Number(x?.[key])||0),0),sales=sum(mv.filter(x=>x.move_type==='ingreso'));if(sales<=0)return'';
  const purchases=sum(docs,'total'),personal=sum(mv.filter(x=>x.move_type==='personal')),expenseRows=mv.filter(x=>x.move_type==='gasto');let operating=sum(expenseRows),taxLoad=0;
  if(typeof expenseTotals==='function'){const t=expenseTotals(expenseRows,selectedMonth);operating=Number(t?.operating)||0;taxLoad=Number(t?.taxLoad)||0}
  const result=sales-purchases-personal-operating-taxLoad,fmt=n=>`${n.toLocaleString('es-ES',{maximumFractionDigits:1})}%`;
  return `<div class="section-title">Ratios del mes</div><div class="card ratio-card"><div class="ratio-title">📐 Estructura sobre ingresos</div><div class="ratio-help">Porcentaje que representa cada bloque sobre los ingresos registrados de ${esc(monthLabel(selectedMonth))}. Es información descriptiva; no aplica objetivos automáticos.</div><div class="ratio-grid"><div class="ratio-box"><span>Compras</span><strong>${fmt(mrPct(purchases,sales))}</strong><small>${euro(purchases)}</small></div><div class="ratio-box"><span>Personal</span><strong>${fmt(mrPct(personal,sales))}</strong><small>${euro(personal)}</small></div><div class="ratio-box"><span>Otros gastos</span><strong>${fmt(mrPct(operating+taxLoad,sales))}</strong><small>${euro(operating+taxLoad)}</small></div><div class="ratio-box ratio-result"><span>Resultado estimado</span><strong>${fmt(mrPct(result,sales))}</strong><small>${euro(result)}</small></div></div></div>`;
}
mrStyles();const prevDashboardMR=dashboard;dashboard=function(){const html=prevDashboardMR(),marker='<div class="section-title">Control del mes</div>';return html.includes(marker)?html.replace(marker,mrCard()+marker):html+mrCard()};const prevBindMR=bind;bind=function(){prevBindMR();mrStyles()};if(session)renderApp();
})();
