(()=>{
function pwStyles(){if(document.getElementById('priceWatchStyle'))return;const s=document.createElement('style');s.id='priceWatchStyle';s.textContent=`.price-watch-card{border-color:#493b36}.price-watch-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.price-watch-title{font-size:1rem;font-weight:950}.price-watch-count{font-size:1.2rem;font-weight:950}.price-watch-list{display:flex;flex-direction:column;gap:8px;margin-top:10px}.price-watch-row{border-top:1px solid #332d2a;padding-top:9px}.price-watch-row:first-child{border-top:0;padding-top:0}.price-watch-top{display:flex;justify-content:space-between;gap:10px}.price-watch-name{font-size:.83rem;font-weight:900}.price-watch-change{font-size:.82rem;font-weight:950;white-space:nowrap}.price-watch-change.up{color:#ff9a91}.price-watch-change.down{color:#7bd79a}.price-watch-meta{font-size:.7rem;color:var(--muted);line-height:1.4;margin-top:3px}.price-watch-open{padding:6px 8px!important;font-size:.68rem!important;margin-top:6px}.price-watch-btn{width:100%;margin-top:10px}`;document.head.appendChild(s)}
function pwNorm(s=''){return String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim()}
function pwChanges(){
  const groups=new Map();
  for(const p of Array.isArray(products)?products:[]){const key=`${pwNorm(p.name)}|${pwNorm(p.unit)}`;if(!key.startsWith('|')){if(!groups.has(key))groups.set(key,[]);groups.get(key).push(p)}}
  const out=[];
  for(const rows of groups.values()){
    rows.sort((a,b)=>String(b.price_date||'').localeCompare(String(a.price_date||''))||String(b.created_at||'').localeCompare(String(a.created_at||'')));
    if(rows.length<2)continue;const now=rows[0],prev=rows[1],a=Number(now.price),b=Number(prev.price);if(!Number.isFinite(a)||!Number.isFinite(b)||b<=0)continue;
    const pct=((a-b)/b)*100;if(Math.abs(pct)<.5)continue;out.push({now,prev,pct});
  }
  return out.sort((a,b)=>Math.abs(b.pct)-Math.abs(a.pct));
}
function pwOpenProduct(name){route='products';renderApp();scrollTo(0,0);setTimeout(()=>{const q=document.getElementById('productSearch');if(!q)return;q.value=name||'';q.dispatchEvent(new Event('input',{bubbles:true}));q.focus()},0)}
function pwCard(){const all=pwChanges(),rows=all.slice(0,5);if(!rows.length)return'';return `<div class="section-title">Cambios de precio</div><div class="card price-watch-card"><div class="price-watch-head"><div><div class="price-watch-title">🏷️ Precios que han cambiado</div><div class="price-watch-meta">Comparo las dos últimas referencias de cada producto y unidad.</div></div><div class="price-watch-count">${all.length}</div></div><div class="price-watch-list">${rows.map(x=>{const up=x.pct>0,pct=Math.abs(x.pct).toLocaleString('es-ES',{minimumFractionDigits:1,maximumFractionDigits:1});return `<div class="price-watch-row"><div class="price-watch-top"><div class="price-watch-name">${esc(x.now.name||'Producto')}</div><div class="price-watch-change ${up?'up':'down'}">${up?'▲ +':'▼ -'}${pct}%</div></div><div class="price-watch-meta">${euro(x.prev.price)} → <strong>${euro(x.now.price)}</strong> · ${esc(x.now.unit||'unidad')}<br>${esc(x.now.supplier||'Sin proveedor')} · ${fmtDate(x.now.price_date)}${x.prev.supplier&&x.prev.supplier!==x.now.supplier?` · antes ${esc(x.prev.supplier)}`:''}</div><button type="button" class="secondary price-watch-open" data-price-watch-product="${esc(x.now.name||'')}">Ver producto</button></div>`}).join('')}</div>${all.length>5?`<div class="price-watch-meta">+ ${all.length-5} cambio${all.length-5===1?'':'s'} más</div>`:''}<button type="button" id="openPriceWatchProducts" class="secondary price-watch-btn">Abrir Productos</button></div>`}
pwStyles();const previousDashboardPriceWatch=dashboard;dashboard=function(){const html=previousDashboardPriceWatch(),marker='<div class="section-title">Control del mes</div>';return html.includes(marker)?html.replace(marker,pwCard()+marker):html+pwCard()};const previousBindPriceWatch=bind;bind=function(){previousBindPriceWatch();pwStyles();document.getElementById('openPriceWatchProducts')?.addEventListener('click',()=>pwOpenProduct(''));document.querySelectorAll('[data-price-watch-product]').forEach(b=>b.addEventListener('click',()=>pwOpenProduct(b.dataset.priceWatchProduct)))};if(session)renderApp();
})();
