(()=>{
const SB_URL='https://mpzemodwiuxqemvfaqvs.supabase.co';
const SB_KEY='sb_publishable_5b0LE9t_UFaHQwsYZ7BvKQ_k_tAmbVc';
const SESSION_KEY='casa-familia-session-v3';
const OLD_KEYS=['casa-familia-session-v2','casa-familia-session-v1','pizarrita-cloud-session-v3',`sb-mpzemodwiuxqemvfaqvs-auth-token`];
const CATS=['Casa','Supermercado','Coche','Familia','Ocio','Restaurantes','Viajes','Salud/Farmacia','Ropa','Suscripciones','Seguros','Gastos personales','Otros'];
let session=null,expenses=[],rules=[],route='home',editingId=null,draftItems=[];
const $=id=>document.getElementById(id);
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const euro=n=>new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR'}).format(Number(n)||0);
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]||c));
const fmtDate=s=>{if(!s)return '';const [y,m,d]=String(s).split('-');return d&&m&&y?`${d}/${m}/${y}`:s};
function toast(m){let t=$('toast');if(!t){t=document.createElement('div');t.id='toast';document.body.appendChild(t)}t.textContent=m;t.className='show';setTimeout(()=>t.className='',2800)}
function decode(token){try{return JSON.parse(atob(token.split('.')[1].replace(/-/g,'+').replace(/_/g,'/')))}catch{return {}}}
function uid(){return session?.user?.id||decode(session?.access_token||'').sub||null}
function tokenExp(){return Number(decode(session?.access_token||'').exp||0)*1000}
function saveSession(s){session=s;localStorage.setItem(SESSION_KEY,JSON.stringify(s))}
async function refresh(){try{if(!session?.refresh_token)return false;const r=await fetch(`${SB_URL}/auth/v1/token?grant_type=refresh_token`,{method:'POST',headers:{apikey:SB_KEY,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:session.refresh_token})});if(!r.ok)return false;saveSession(await r.json());return true}catch{return false}}
async function ensureFresh(){if(!session?.access_token)return false;if(tokenExp()-Date.now()<120000)return await refresh();return true}
async function request(path,{method='GET',body,headers={}}={}){await ensureFresh();const h={apikey:SB_KEY,...headers};if(session?.access_token)h.Authorization=`Bearer ${session.access_token}`;if(body!==undefined)h['Content-Type']='application/json';let r=await fetch(SB_URL+path,{method,headers:h,body:body===undefined?undefined:JSON.stringify(body)});if(r.status===401&&await refresh()){h.Authorization=`Bearer ${session.access_token}`;r=await fetch(SB_URL+path,{method,headers:h,body:body===undefined?undefined:JSON.stringify(body)})}const text=await r.text();let d;try{d=text?JSON.parse(text):null}catch{d=text}if(!r.ok)throw new Error(d?.message||d?.error_description||d?.error||`Error ${r.status}`);return d}
async function validate(s){try{session=s;if(tokenExp()-Date.now()<120000&&!await refresh())return false;const u=await request('/auth/v1/user');saveSession({...session,user:u});return true}catch{return false}}
async function restore(){for(const k of [SESSION_KEY,...OLD_KEYS]){try{const v=JSON.parse(localStorage.getItem(k)||'null');for(const s of [v,v?.session,v?.currentSession,v?.data?.session,v?.data])if(s?.access_token&&s?.refresh_token&&await validate(s))return true}catch{}}return false}
async function login(email,password){const r=await fetch(`${SB_URL}/auth/v1/token?grant_type=password`,{method:'POST',headers:{apikey:SB_KEY,'Content-Type':'application/json'},body:JSON.stringify({email,password})});const d=await r.json();if(!r.ok)throw new Error(d.error_description||d.msg||'No se ha podido entrar');saveSession(d);await validate(d)}
async function load(){const [e,r]=await Promise.all([request('/rest/v1/home_expenses?select=*&order=expense_date.desc,created_at.desc'),request('/rest/v1/home_expense_rules?select=*&order=created_at.desc')]);expenses=e||[];rules=r||[];render()}
function sum(f){return expenses.filter(f).reduce((a,x)=>a+Number(x.amount||0),0)}
function totals(){const d=new Date(),t=today(),month=t.slice(0,7),year=t.slice(0,4),monday=new Date(d);monday.setDate(d.getDate()-((d.getDay()+6)%7));const mon=`${monday.getFullYear()}-${String(monday.getMonth()+1).padStart(2,'0')}-${String(monday.getDate()).padStart(2,'0')}`;return{day:sum(x=>x.expense_date===t),week:sum(x=>x.expense_date>=mon&&x.expense_date<=t),month:sum(x=>x.expense_date?.startsWith(month)),year:sum(x=>x.expense_date?.startsWith(year))}}
function normalizeItems(items){const num=v=>{if(v===null||v===undefined||v==='')return null;const n=Number(String(v).replace(',','.'));return Number.isFinite(n)?n:null};return Array.isArray(items)?items.map(i=>({name:String(i?.name||'').trim(),quantity:num(i?.quantity),unit_price:num(i?.unit_price),line_total:num(i?.line_total)})).filter(i=>i.name):[]}
function productLines(items){const a=normalizeItems(items);if(!a.length)return '';return `<details class="products"><summary>🛒 ${a.length} producto${a.length===1?'':'s'}</summary><div class="product-list">${a.map(i=>`<div class="product-line"><div><b>${esc(i.name)}</b><small>${i.quantity!=null?`${i.quantity} ud.`:''}${i.unit_price!=null?`${i.quantity!=null?' · ':''}${euro(i.unit_price)}/ud.`:''}</small></div><strong>${i.line_total!=null?euro(i.line_total):''}</strong></div>`).join('')}</div></details>`}
function nav(){return `<nav><button data-r="home">Inicio</button><button data-r="list">Gastos</button><button class="plus" data-r="add">＋</button><button data-r="fixed">Fijos</button><button data-r="more">Más</button></nav>`}
function shell(body){return `<div class="top"><div><small>CASA & FAMILIA</small><h1>Control del hogar</h1></div><span>☁ Nube</span></div><main>${body}</main>${nav()}`}
function row(x){return `<div class="expense-card"><div class="row"><div><b>${esc(x.concept)}</b><small>${esc(x.category)} · ${fmtDate(x.expense_date)}</small><div><button data-edit="${x.id}">Editar</button>${x.file_path?`<button data-file="${esc(x.file_path)}">Ticket</button>`:''}<button data-del="${x.id}">Borrar</button></div></div><strong>${euro(x.amount)}</strong></div>${productLines(x.items)}</div>`}
function home(){const t=totals(),recent=expenses.slice(0,5);return shell(`<section class="hero"><small>Total gastado este mes</small><div>${euro(t.month)}</div></section><section class="grid"><article>Hoy<b>${euro(t.day)}</b></article><article>Semana<b>${euro(t.week)}</b></article><article>Mes<b>${euro(t.month)}</b></article><article>Año<b>${euro(t.year)}</b></article></section><h2>Últimos gastos</h2><section class="card">${recent.length?recent.map(row).join(''):'<p>No hay gastos todavía.</p>'}</section>`)}
function list(){return shell(`<h2>Gastos</h2><section class="card">${expenses.length?expenses.map(row).join(''):'<p>No hay gastos todavía.</p>'}</section>`)}
function draftHtml(items){const a=normalizeItems(items);if(!a.length)return '<p class="hint">Cuando la IA lea el ticket, aquí aparecerán los productos comprados.</p>';return `<div class="detected"><b>Productos detectados: ${a.length}</b>${a.map(i=>`<div class="product-line"><div><b>${esc(i.name)}</b><small>${i.quantity!=null?`${i.quantity} ud.`:''}${i.unit_price!=null?`${i.quantity!=null?' · ':''}${euro(i.unit_price)}/ud.`:''}</small></div><strong>${i.line_total!=null?euro(i.line_total):''}</strong></div>`).join('')}</div>`}
function add(){const x=editingId?expenses.find(v=>v.id===editingId):null;const existing=x?normalizeItems(x.items):draftItems;return shell(`<h2>${x?'Editar gasto':'Añadir gasto'}</h2><section class="card form"><label>Fecha<input id="date" type="date" value="${esc(x?.expense_date||today())}"></label><label>Importe<input id="amount" inputmode="decimal" placeholder="0,00" value="${x?String(x.amount).replace('.',','):''}"></label><label>Concepto <em>(opcional)</em><input id="concept" placeholder="Ej. Mercadona, luz..." value="${esc(x?.concept||'')}"></label><label>Categoría<select id="cat">${CATS.map(c=>`<option ${x?.category===c?'selected':''}>${c}</option>`).join('')}</select></label>${x?`<div id="itemsPreview">${draftHtml(existing)}</div>`:`<label>Foto del ticket <em>(opcional)</em><input id="file" type="file" accept="image/*,application/pdf" capture="environment"></label><button id="ai" class="ai">✨ Leer ticket con IA</button><div id="itemsPreview">${draftHtml(draftItems)}</div>`}<button id="save" class="save">${x?'Guardar cambios':'Guardar gasto'}</button>${x?'<button id="cancel">Cancelar</button>':''}</section>`)}
function fixed(){return shell(`<h2>Gastos fijos</h2><section class="card form"><label>Concepto<input id="rc" placeholder="Ej. Internet"></label><label>Importe<input id="ra" inputmode="decimal" placeholder="0,00"></label><label>Categoría<select id="rCat">${CATS.map(c=>`<option>${c}</option>`).join('')}</select></label><label>Fecha inicial<input id="rd" type="date" value="${today()}"></label><button id="saveRule" class="save">Añadir gasto fijo mensual</button></section><section class="card">${rules.length?rules.map(r=>`<div class="row"><div><b>${esc(r.concept)}</b><small>${esc(r.category)} · ${euro(r.amount)}</small><div><button data-rule="${r.id}" data-active="${r.active}">${r.active?'Pausar':'Reactivar'}</button><button data-rdel="${r.id}">Borrar</button></div></div></div>`).join(''):'<p>No hay gastos fijos.</p>'}</section>`)}
function more(){return shell(`<h2>Más</h2><section class="card"><p>${esc(session?.user?.email||'')}</p><button id="logout">Cerrar sesión</button></section>`)}
function render(){$('root').innerHTML=route==='home'?home():route==='list'?list():route==='add'?add():route==='fixed'?fixed():more();bind()}
function valAmount(id){const s=$(id)?.value.trim().replace(/\s/g,'').replace(',','.');const n=Number(s);return Number.isFinite(n)?n:null}
async function saveExpense(){const amount=valAmount('amount'),date=$('date').value,cat=$('cat').value||'Otros',concept=$('concept').value.trim()||cat;if(amount===null||amount<0)return toast('Pon un importe válido');try{let body={expense_date:date,concept,category:cat,amount,updated_at:new Date().toISOString()};if(editingId){const old=expenses.find(x=>x.id===editingId);body.items=normalizeItems(old?.items);const rows=await request(`/rest/v1/home_expenses?id=eq.${editingId}&select=*`,{method:'PATCH',headers:{Prefer:'return=representation'},body});expenses=expenses.map(x=>x.id===editingId?rows[0]:x);editingId=null}else{const id=uid();if(!id)throw new Error('Sesión no válida. Vuelve a entrar.');const f=$('file')?.files?.[0];if(f)body.file_path=await upload(f);body.user_id=id;body.items=normalizeItems(draftItems);const rows=await request('/rest/v1/home_expenses?select=*',{method:'POST',headers:{Prefer:'return=representation'},body});expenses.unshift(rows[0]);draftItems=[]}route='home';render();toast('Gasto guardado')}catch(e){toast('No se pudo guardar: '+e.message)}}
async function upload(file){await ensureFresh();const id=uid();const ext=(file.name.split('.').pop()||'jpg').replace(/[^a-z0-9]/gi,'')||'jpg';const path=`${id}/home/${today().slice(0,7)}/${Date.now()}-${Math.random().toString(36).slice(2)}.${ext}`;let r=await fetch(`${SB_URL}/storage/v1/object/invoice-files/${path}`,{method:'POST',headers:{apikey:SB_KEY,Authorization:`Bearer ${session.access_token}`,'Content-Type':file.type||'application/octet-stream'},body:file});if(r.status===401&&await refresh())r=await fetch(`${SB_URL}/storage/v1/object/invoice-files/${path}`,{method:'POST',headers:{apikey:SB_KEY,Authorization:`Bearer ${session.access_token}`,'Content-Type':file.type||'application/octet-stream'},body:file});if(!r.ok)throw new Error('No se pudo subir la foto');return path}
function toData(file){return new Promise((ok,no)=>{const r=new FileReader();r.onload=()=>ok(r.result);r.onerror=no;r.readAsDataURL(file)})}
async function readAI(){const f=$('file')?.files?.[0];if(!f)return toast('Haz una foto o selecciona un ticket primero');try{$('ai').disabled=true;$('ai').textContent='Leyendo…';if(!await ensureFresh())throw new Error('Sesión no válida. Vuelve a entrar.');const dataUrl=await toData(f);let r=await fetch('/api/home-expense-ai',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({dataUrl,name:f.name,type:f.type})});if(r.status===401&&await refresh())r=await fetch('/api/home-expense-ai',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({dataUrl,name:f.name,type:f.type})});const text=await r.text();let d;try{d=JSON.parse(text)}catch{}if(!r.ok||!d)throw new Error(d?.error||'No se pudo leer');const x=d.expense||{};if(x.date)$('date').value=x.date;if(x.amount!=null)$('amount').value=String(x.amount).replace('.',',');if(x.concept)$('concept').value=x.concept;if(CATS.includes(x.category))$('cat').value=x.category;draftItems=normalizeItems(x.items);if($('itemsPreview'))$('itemsPreview').innerHTML=draftHtml(draftItems);toast(draftItems.length?`Ticket leído · ${draftItems.length} productos`:'Ticket leído. No he podido separar productos.')}catch(e){toast('IA: '+e.message)}finally{if($('ai')){$('ai').disabled=false;$('ai').textContent='✨ Leer ticket con IA'}}}
async function deleteExpense(id){if(!confirm('¿Borrar este gasto?'))return;try{await request(`/rest/v1/home_expenses?id=eq.${id}`,{method:'DELETE'});expenses=expenses.filter(x=>x.id!==id);render();toast('Gasto borrado')}catch(e){toast(e.message)}}
async function openFile(path){try{await ensureFresh();const r=await fetch(`${SB_URL}/storage/v1/object/sign/invoice-files/${path}`,{method:'POST',headers:{apikey:SB_KEY,Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({expiresIn:120})});const d=await r.json();if(!r.ok)throw new Error('No se pudo abrir');window.open(`${SB_URL}/storage/v1${d.signedURL}`,'_blank')}catch(e){toast(e.message)}}
async function saveRule(){const amount=valAmount('ra'),concept=$('rc').value.trim(),cat=$('rCat').value,date=$('rd').value;if(!concept||amount===null)return toast('Completa concepto e importe');try{const rows=await request('/rest/v1/home_expense_rules?select=*',{method:'POST',headers:{Prefer:'return=representation'},body:{user_id:uid(),concept,category:cat,amount,start_date:date,cadence:'monthly',active:true}});rules.unshift(rows[0]);render();toast('Gasto fijo añadido')}catch(e){toast(e.message)}}
async function toggleRule(id,active){try{const rows=await request(`/rest/v1/home_expense_rules?id=eq.${id}&select=*`,{method:'PATCH',headers:{Prefer:'return=representation'},body:{active:!active,updated_at:new Date().toISOString()}});rules=rules.map(x=>x.id===id?rows[0]:x);render()}catch(e){toast(e.message)}}
async function delRule(id){if(!confirm('¿Borrar este gasto fijo?'))return;try{await request(`/rest/v1/home_expense_rules?id=eq.${id}`,{method:'DELETE'});rules=rules.filter(x=>x.id!==id);render()}catch(e){toast(e.message)}}
function bind(){document.querySelectorAll('[data-r]').forEach(b=>b.onclick=()=>{route=b.dataset.r;editingId=null;if(route==='add')draftItems=[];render()});document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{editingId=b.dataset.edit;route='add';render()});document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>deleteExpense(b.dataset.del));document.querySelectorAll('[data-file]').forEach(b=>b.onclick=()=>openFile(b.dataset.file));document.querySelectorAll('[data-rule]').forEach(b=>b.onclick=()=>toggleRule(b.dataset.rule,b.dataset.active==='true'));document.querySelectorAll('[data-rdel]').forEach(b=>b.onclick=()=>delRule(b.dataset.rdel));$('save')?.addEventListener('click',saveExpense);$('ai')?.addEventListener('click',readAI);$('file')?.addEventListener('change',()=>{draftItems=[];if($('itemsPreview'))$('itemsPreview').innerHTML=draftHtml([]);if($('file').files?.[0])toast('Foto seleccionada. Pulsa “Leer ticket con IA”.')});$('cancel')?.addEventListener('click',()=>{editingId=null;route='list';render()});$('saveRule')?.addEventListener('click',saveRule);$('logout')?.addEventListener('click',async()=>{try{await request('/auth/v1/logout',{method:'POST'})}catch{}for(const k of [SESSION_KEY,...OLD_KEYS])localStorage.removeItem(k);session=null;loginScreen()})}
function loginScreen(){$('root').innerHTML=`<div class="login"><section class="card form"><h1>Casa & Familia</h1><label>Correo<input id="email" type="email"></label><label>Contraseña<input id="pass" type="password"></label><button id="enter" class="save">Entrar</button><p id="status"></p></section></div>`;$('enter').onclick=async()=>{try{$('status').textContent='Entrando…';await login($('email').value.trim(),$('pass').value);await load()}catch(e){$('status').textContent=e.message}}}
(async()=>{if(await restore())await load();else loginScreen()})();
})();