(()=>{
const SB_URL='https://mpzemodwiuxqemvfaqvs.supabase.co';
const SB_KEY='sb_publishable_5b0LE9t_UFaHQwsYZ7BvKQ_k_tAmbVc';
const SESSION_KEYS=['casa-familia-session-v3','casa-familia-session-v2','casa-familia-session-v1','pizarrita-cloud-session-v3','sb-mpzemodwiuxqemvfaqvs-auth-token'];
const euro=n=>new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR'}).format(Number(n)||0);
const qty=n=>new Intl.NumberFormat('es-ES',{maximumFractionDigits:2}).format(Number(n)||0);
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]||c));
const fmtDate=s=>{if(!s)return '';const [y,m,d]=String(s).split('-');return d&&m&&y?`${d}/${m}/${y}`:s};
function parse(v){try{return JSON.parse(v||'null')}catch{return null}}
function asSession(v){for(const x of [v,v?.session,v?.currentSession,v?.data?.session,v?.data])if(x?.access_token)return x;return null}
function getSession(){for(const k of SESSION_KEYS){const s=asSession(parse(localStorage.getItem(k)));if(s)return s}return null}
function number(v){if(v===null||v===undefined||v==='')return null;const n=Number(String(v).replace(',','.'));return Number.isFinite(n)?n:null}
function normName(s){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()}
async function loadExpenses(){const s=getSession();if(!s?.access_token)throw new Error('No encuentro la sesión. Cierra y abre la app otra vez.');const r=await fetch(`${SB_URL}/rest/v1/home_expenses?select=id,expense_date,items&order=expense_date.desc`,{headers:{apikey:SB_KEY,Authorization:`Bearer ${s.access_token}`}});if(!r.ok)throw new Error('No he podido cargar los productos. Vuelve a abrir la app.');return await r.json()}
function aggregate(expenses){const map=new Map();for(const e of expenses||[]){const seen=new Set();for(const i of Array.isArray(e.items)?e.items:[]){const name=String(i?.name||'').trim();if(!name)continue;const key=normName(name);if(!key)continue;let x=map.get(key);if(!x){x={name,quantity:0,spent:0,tickets:0,lastDate:e.expense_date||'',lines:0};map.set(key,x)}const q=number(i?.quantity);const unit=number(i?.unit_price);const total=number(i?.line_total);x.quantity+=q==null?1:q;x.spent+=total!=null?total:(unit!=null?unit*(q==null?1:q):0);x.lines++;if(!seen.has(key)){x.tickets++;seen.add(key)}if((e.expense_date||'')>x.lastDate)x.lastDate=e.expense_date||''}}
return [...map.values()].sort((a,b)=>b.quantity-a.quantity||b.tickets-a.tickets||b.spent-a.spent||a.name.localeCompare(b.name,'es'))}
function productRows(rows){if(!rows.length)return '<p class="hint">Todavía no hay productos leídos en los tickets.</p>';return rows.map((x,i)=>`<div class="product-stat-row" data-name="${esc(normName(x.name))}" style="display:flex;align-items:center;gap:12px;padding:13px 0;border-bottom:1px solid #1c3b57"><div style="width:30px;color:#62e1c7;font-weight:900">${i+1}</div><div style="flex:1;min-width:0"><b style="display:block">${esc(x.name)}</b><small style="display:block;color:#9db3ca;margin-top:4px">${qty(x.quantity)} acumulado · ${x.tickets} compra${x.tickets===1?'':'s'}${x.lastDate?` · última ${fmtDate(x.lastDate)}`:''}</small></div><strong style="white-space:nowrap">${euro(x.spent)}</strong></div>`).join('')}
function render(rows){const main=document.querySelector('main');if(!main)return;const totalQty=rows.reduce((a,x)=>a+x.quantity,0);const totalSpent=rows.reduce((a,x)=>a+x.spent,0);main.innerHTML=`<h2>Productos</h2><section class="card"><div class="grid" style="margin-bottom:14px"><article>Productos distintos<b>${rows.length}</b></article><article>Cantidad acumulada<b>${qty(totalQty)}</b></article><article style="grid-column:1/-1">Gasto identificado en productos<b>${euro(totalSpent)}</b></article></div><label style="color:#b6c6d5;font-size:.88rem">Buscar producto<input id="productSearch" placeholder="Ej. leche, agua, yogur..."></label><p class="hint" style="margin-top:10px">Se suman automáticamente todos los productos leídos de todos los tickets. Si vuelves a comprar el mismo producto, aumenta su cantidad, sus compras y el gasto acumulado.</p></section><section class="card"><div style="display:flex;justify-content:space-between;gap:10px;align-items:end;margin-bottom:8px"><div><b style="font-size:1.05rem">Más consumidos</b><small style="display:block;color:#9db3ca;margin-top:3px">Ordenados por cantidad acumulada</small></div></div><div id="productRanking">${productRows(rows)}</div></section>`;
const search=document.getElementById('productSearch');search?.addEventListener('input',()=>{const q=normName(search.value);document.querySelectorAll('.product-stat-row').forEach(r=>{r.style.display=!q||r.dataset.name.includes(q)?'flex':'none'})});
}
async function showProducts(){const main=document.querySelector('main');if(main)main.innerHTML='<h2>Productos</h2><section class="card"><p>Cargando consumo acumulado…</p></section>';document.querySelectorAll('nav button').forEach(b=>b.style.color='');const tab=document.getElementById('productsNav');if(tab)tab.style.color='#62e1c7';try{const expenses=await loadExpenses();render(aggregate(expenses))}catch(e){if(main)main.innerHTML=`<h2>Productos</h2><section class="card"><p>${esc(e.message)}</p></section>`}}
function ensureNav(){const nav=document.querySelector('nav');if(!nav)return;if(nav.style.gridTemplateColumns!=='repeat(6, 1fr)')nav.style.gridTemplateColumns='repeat(6, 1fr)';if(document.getElementById('productsNav'))return;const b=document.createElement('button');b.id='productsNav';b.type='button';b.textContent='Productos';b.addEventListener('click',showProducts);const last=nav.lastElementChild;nav.insertBefore(b,last)}
let queued=false;const observer=new MutationObserver(()=>{if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;ensureNav()})});observer.observe(document.documentElement,{childList:true,subtree:true});ensureNav();
})();